name: 同步&合并
on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:
jobs:
  merge-branch:
    env:
      PAT: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v2
        with:
          persist-credentials: fals 

      - name: git-sync gitee/lxk0301/jd_scripts.git to github with private key
        uses: wei/git-sync@v3
        with:
          source_repo: "git@jd_base_gitee:supermanito/jd_base.git"
          source_branch: "master"
          destination_repo: "nxppru/jdcc"
          destination_branch: "dev"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY'
